name: 'Validate release notes'
description: 'Check if a specified label is present on a PR, and, if so, ensure release notes exist.'
inputs:
  label-name:  # id of input
    description: 'The Github label that we want to check for'
    required: true
    default: 'release-note-required'
outputs:
  time: # id of output
    description: 'The release notes that were found'
runs:
  using: 'node20'
  main: 'dist/index.js'